Update databases.md
MicrosoftDocs/architecture-center pull request #2993
Opened 2021-08-02 18:47 UTC by splitfinity

Made a few changes:
- Added a link for SQL Managed Instance
- Updated link and description for synapse analytics
- Updated description for power bi

2021-08-02 18:48 UTC, PRMerger7 commented
@splitfinity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-02 21:42 UTC, PRMerger8 commented
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

2021-08-02 21:42 UTC, EdPrice-MSFT submitted a review, later dismissed
Fantastic updates!

2021-08-02 21:42 UTC, EdPrice-MSFT submitted a review, later dismissed
Fantastic updates!

2021-08-02 21:43 UTC, EdPrice-MSFT commented
#Sign-Off

2021-08-02 21:43 UTC, PRMerger7 commented
@EdPrice-MSFT: I'm sorry - only the author of this article, @splitfinity, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-08-04 21:51 UTC, ShannonLeavitt commented on docs/aws-professional/databases.md
> +- [Power BI](https://powerbi.microsoft.com): a business analytics service that provides the capabilities to creach rich interactive data visualizations.
```suggestion
- [Power BI](https://powerbi.microsoft.com): a business analytics service that provides the capabilities to create rich interactive data visualizations.
```
Fixing typo

2021-08-09 16:25 UTC, akdataai commented
Can I suggest adding specific Cosmos documentation to mirror the GCP offerings of BigTable, Firestore, Firebase. 

Cloud Bigtable - Cosmos DB Cassandra API
Cloud Firestore - Cosmos DB Mongo API
Cloud Firebase Realtime Database - Cosmos DB Change Feed

I'd also include Cosmos DB analytical store against Google Bigtable 

Are we missing Google Datastore, for which we would have Cosmos DB SQL API

2021-08-09 16:47 UTC, akdataai requested changes
Can we expand this to include Cosmos and all it's features including Cosmos Analytical Store and Change Feed.

Also references to Cortana AI Suite should be changed to Azure AI Platform?

2021-08-09 21:22 UTC, EdPrice-MSFT approved these changes
Good changes

2021-08-09 21:22 UTC, EdPrice-MSFT commented
#Sign-Off

2021-08-09 21:22 UTC, PRMerger17 commented
@EdPrice-MSFT: I'm sorry - only the author of this article, @splitfinity, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-08-09 21:48 UTC, ktoliver commented
I moved the commits to the private repo to take advantage of automated metadata and link validation. I'll close this pull request. The new PR will be merged soon.

2021-08-09 21:48 UTC, closed without merging