Updated sync-mainframe-data-with-azure-content.md  with Azure Synapse…
MicrosoftDocs/architecture-center pull request #3432
Opened 2022-05-17 16:53 UTC by msdnguy

… integration option

Azure Synapse native DB2 connector allows direct integration to Mainframe and Midrange platforms.

2022-05-18 18:10 UTC, PRMerger13 commented
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2022-05-18 18:55 UTC, bhbandam approved these changes

2022-05-18 18:55 UTC, bhbandam approved these changes

2022-05-18 18:59 UTC, bhbandam commented
#sign-off

2022-05-18 18:59 UTC, PRMerger17 commented
@bhbandam: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2022-05-18 19:02 UTC, bhbandam commented
Can you please merge this request ?

Bhaskar Bandam
Senior Program Manager
Azure Global Engineering
Office: +1 703 673 7887 | Mobile: +1 703 581 3678 | Email: ***@***.******@***.***>
***@***.***



From: PRMerger17 ***@***.***>
Sent: Wednesday, May 18, 2022 3:00 PM
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Bhaskar Bandam ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/architecture-center] Updated sync-mainframe-data-with-azure-content.md with Azure Synapse… (PR #3432)


@bhbandam<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbhbandam&data=05%7C01%7Cbhaskar.bandam%40microsoft.com%7C83e4b4ee6fd44c57473d08da39009ec9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637884972076690929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YAh%2FMBQJw162csyfdNCXcDQxTUeTAfh9zaftkS4nNwc%3D&reserved=0>: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Farchitecture-center%2Fpull%2F3432%23issuecomment-1130394792&data=05%7C01%7Cbhaskar.bandam%40microsoft.com%7C83e4b4ee6fd44c57473d08da39009ec9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637884972076690929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IMNabqfm2Uvrk90k3hQ%2F1HHnwpR1DloBEAWYI4z6xZU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPCSSHCBE62GEBOS75PRXD3VKU43JANCNFSM5WFSNDGQ&data=05%7C01%7Cbhaskar.bandam%40microsoft.com%7C83e4b4ee6fd44c57473d08da39009ec9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637884972076690929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dluH34yM25H22pRsweqmTyUrqLVL%2B0OsB2cwHPeYpL4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-05-18 19:03 UTC, bhbandam submitted a review, later dismissed

2022-05-18 21:28 UTC, ckittel requested changes

2022-05-18 21:28 UTC, ckittel commented on docs/reference-architectures/migration/sync-mainframe-data-with-azure-content.md
> +[Azure Synapse Analytics] /azure/synapse-analytics/overview-what-is
```suggestion
[Azure Synapse Analytics]: /azure/synapse-analytics/overview-what-is
```

2022-05-18 21:28 UTC, ckittel commented on docs/reference-architectures/migration/sync-mainframe-data-with-azure-content.md
> +- [Azure Synapse Analytics] is an enterprise analytics service that accelerates time to insight, across data warehouses and big data systems. Azure Synapse brings together the best of SQL technologie
```suggestion
- [Azure Synapse Analytics][Azure Synapse Analytics] is an enterprise analytics service that accelerates time to insight, across data warehouses and big data systems. Azure Synapse brings together the best of SQL technologies (that are used in enterprise data warehousing), Spark technologies used for big data, Data Explorer for log and time series analytics, Pipelines for data integration and ETL/ELT, and deep integration with other Azure services, such as Power BI, Cosmos DB, and Azure Machine Learning.
```

2022-05-18 22:31 UTC, ckittel approved these changes
Lgtm

2022-05-18 23:57 UTC, merged

2022-10-11 08:10 UTC, msdnguy commented
Hi Chad,

I approved the change.  Sorry about the sloppy markdown.

marc

From: Chad Kittel ***@***.***>
Sent: Wednesday, May 18, 2022 3:30 PM
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Marc Wolfson ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftDocs/architecture-center] Updated sync-mainframe-data-with-azure-content.md with Azure Synapse… (PR #3432)


@bhbandam<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbhbandam&data=05%7C01%7Cmwolfson%40microsoft.com%7C66d77cda5ca143aacaf208da391dff52%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637885098245917581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JlD981ghezJVmx%2Fyyr%2FCOnsoKrMQSNCesOtPegyAoJ0%3D&reserved=0>, @ckittel<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fckittel&data=05%7C01%7Cmwolfson%40microsoft.com%7C66d77cda5ca143aacaf208da391dff52%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637885098245917581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6Jy8cLM2rpzkdhVW2gycSRIbUTvFEQvQcaA1DS%2F08II%3D&reserved=0> recently requested changes in his review. Do those changes still need to be made, or should it be merged as is?

They fix build errors, so we shouldn't merge until resolved. Otherwise we have to fix them on the backend.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Farchitecture-center%2Fpull%2F3432%23issuecomment-1130637247&data=05%7C01%7Cmwolfson%40microsoft.com%7C66d77cda5ca143aacaf208da391dff52%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637885098245917581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E8mWluJFi2QXE6zdLHKAPRJ4okTG7q7hTYGBSTz4Od4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIDX6KF7J5O2S5Z3M2DVRBTVKVVP5ANCNFSM5WFSNDGQ&data=05%7C01%7Cmwolfson%40microsoft.com%7C66d77cda5ca143aacaf208da391dff52%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637885098245917581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lOV5FjWMOYCGqoPJWX1iJUwMgyaeesBFplZKRJ5HF5I%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>