chore: Included githubactions in the dependabot config
MicrosoftDocs/architecture-center pull request #3450
Opened 2022-05-27 01:31 UTC by naveensrinivasan

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

2022-05-27 16:40 UTC, Court72 commented
@EdPrice-MSFT 

Can you review the proposed changes? The commits should be moved into the private repo to benefit from validation as well.

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

2022-05-27 22:33 UTC, EdPrice-MSFT commented
@ckittel or @josevarela - This one too? Thanks!

2022-06-01 14:23 UTC, ckittel requested changes

2022-06-01 14:23 UTC, ckittel commented on .github/dependabot.yml
> +      interval: "weekly"
```suggestion
    interval: "weekly"
```

2022-06-01 14:29 UTC, ckittel commented
I'm going to close this one in retrospect.  This repo isn't the place where we'd want to open this PR as we have a "backing repo" for this instead, these PRs would be noise in the public repo.  This repo is synced from a backend repo and is only here to support issues and PRs to adjust content.  Thank you though @naveensrinivasan!

2022-06-01 14:29 UTC, closed without merging