Linking to libraries which implement the design consideration
MicrosoftDocs/architecture-center pull request #3690
Opened 2022-10-06 11:09 UTC by udidahan

2022-10-06 11:11 UTC, opbld30 commented
Learn Build status updates of commit _[0416c2f](https://github.com/udidahan/architecture-center/commits/0416c2f335582471fdec8cfd7372c9c3f7dee04c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/auto-scaling.md](https://github.com/udidahan/architecture-center/blob/patch-4/docs/best-practices/auto-scaling.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/f4a29f81-cf18-2571-0853-fc5e34d298ab/202210061109213951-3690/BuildReport?accessString=3b2055792d87c9fcf827e099e6f0ec0f21c1929594058fd6f17bc9961b429e5b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/f4a29f81-cf18-2571-0853-fc5e34d298ab?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:24 UTC, ckittel approved these changes
LGTM

2022-10-06 21:24 UTC, ckittel commented
#sign-off

2022-10-06 23:32 UTC, opbld31 commented
Learn Build status updates of commit _[a7a8ac7](https://github.com/udidahan/architecture-center/commits/a7a8ac7eecdc0ab74f13329d13a8c9d5a246894f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/auto-scaling.md](https://github.com/udidahan/architecture-center/blob/patch-4/docs/best-practices/auto-scaling.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/f4a29f81-cf18-2571-0853-fc5e34d298ab/202210062331467796-3690/BuildReport?accessString=49e5ad8925cdfdfd8373aef3a68e7fac1ca98159ff691ef21b6e8a3d80919da2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/f4a29f81-cf18-2571-0853-fc5e34d298ab?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 12:45 UTC, ckittel requested changes

2022-10-07 12:45 UTC, ckittel commented on docs/best-practices/auto-scaling.md
> +ms.date: 10/07/2022
We didn't do a maintenance review this article yet, and should still be in the queue for maintenance.  Please revert the date change.  Thanks.

```suggestion
ms.date: 05/17/2017
```

2022-10-08 08:08 UTC, EdPrice-MSFT approved these changes
Looks good

2022-10-08 08:08 UTC, opbld32 commented
Learn Build status updates of commit _[be86328](https://github.com/udidahan/architecture-center/commits/be863285a2e6af86cefd3e69cd134f5606e77878)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/auto-scaling.md](https://github.com/udidahan/architecture-center/blob/patch-4/docs/best-practices/auto-scaling.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/f4a29f81-cf18-2571-0853-fc5e34d298ab/202210080807571147-3690/BuildReport?accessString=2dd963dff3929b024e05b96439d8f0e369cd3953582c524c6cf0f5597821338d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/f4a29f81-cf18-2571-0853-fc5e34d298ab?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 08:09 UTC, EdPrice-MSFT commented
#Sign-Off

2022-10-10 14:44 UTC, Court72 approved these changes

2022-10-10 14:48 UTC, Court72 commented
Hi @ckittel, @EdPrice-MSFT 

Merging is still blocked due to outstanding requested changes. Can you resolve the issue and `#sign-off` on the PR again?

Thanks

![image](https://user-images.githubusercontent.com/62625502/194893755-3d39f411-3b4e-4660-ab39-1e07e9a0f328.png)

2022-10-10 14:49 UTC, ckittel approved these changes
LGTM

2022-10-10 14:52 UTC, merged

2022-10-11 04:46 UTC, udidahan commented
Thanks everyone :)